services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: pos_dev
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:17
    environment:
      POSTGRES_DB: pos_test
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password
    ports:
      - "5433:5432"

volumes:
  postgres_data:
